
  publications: [
 
   
 
   
    {
      "id": 3,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Traffic Management in IoT Backbone Networks Using GNN and MAB with SDN Orchestration",
      "journal": "Sensors",
      "volume": "23",
      "year": "2023",
      "indexing": "SCOPUS, Web of Science - SCIE",
      "impactFactor": "3.847",
      "quartile": "Q2",
      "doi": "",
      "academicYear": "2023-2024"
    },
    {
      "id": 4,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "An enterprise blockchain model: A reliable cryptography-based cyber-physical systems for securing user data",
      "journal": "Journal of Discrete Mathematical Sciences and Cryptography",
      "volume": "28",
      "year": "2025",
      "indexing": "SCOPUS, Web of Science - ESCI",
      "impactFactor": "1.3",
      "quartile": "Q2",
      "doi": "",
      "academicYear": "2025-2026"
    },
    {
      "id": 5,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "CXR Images and ELM based Advanced Method for Classification of Multivariant Pneumonia",
      "journal": "2023 International Conference on Inventive Computation Technologies (ICICT)",
      "volume": "",
      "year": "2023",
      "indexing": "IEEE, SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2022-2023"
    },
    {
      "id": 6,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "DNA Sequence based Advanced Technique for Prediction of Hereditary Diseases using Support Vector Machine (SVM)",
      "journal": "6th International Conference on Inventive Computation Technologies, ICICT 2023",
      "volume": "",
      "year": "2023",
      "indexing": "IEEE, SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2022-2023"
    },
 
    {
      "id": 9,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Data Visualisation Models for Analytics use Artificial Intelligence to Predict Diabetes in Women",
      "journal": "Journal of Machine and Computing",
      "volume": "5",
      "year": "2025",
      "indexing": "SCOPUS",
      "impactFactor": "0.15",
      "quartile": "Q2",
      "doi": "",
      "academicYear": "2025-2026"
    },
    {
      "id": 10,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Machine learning-driven predictive maintenance models for hydrogen fuel cell systems in smart transportation networks",
      "journal": "Clean Energy Science and Technology",
      "volume": "4",
      "year": "2026",
      "indexing": "SCOPUS",
      "impactFactor": "2.93",
      "quartile": "Q3",
      "doi": "",
      "academicYear": "2025-2026"
    },
    {
      "id": 11,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Deep SEM: Integrating deep neural networks into structural equation modelling with the SEMdeep package in R",
      "journal": "Methodological Innovations",
      "volume": "23",
      "year": "2026",
      "indexing": "SCOPUS",
      "impactFactor": "0.71",
      "quartile": "Q1",
      "doi": "",
      "academicYear": "2025-2026"
    },
    {
      "id": 12,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Revolutionizing Healthcare: A Smart Pill Detection System Empowered by Deep Learning for Intelligent Drug Recognition",
      "journal": "TQCEBT 2024 - 2nd IEEE International Conference on Trends in Quantum Computing and Emerging Business Technologies",
      "volume": "",
      "year": "2024",
      "indexing": "SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2024-2025"
    },
    {
      "id": 13,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Nonlinear Analysis And Processing Of Software Development, Financial Data, And Marketing Insights Under Internet Of Things Monitoring System",
      "journal": "International Journal of Environmental Sciences",
      "volume": "11",
      "year": "2025",
      "indexing": "SCOPUS",
      "impactFactor": "0.166",
      "quartile": "Q3",
      "doi": "",
      "academicYear": "2025-2026"
    },
    {
      "id": 14,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Prosody Predictor based Diffusion Models Techniques for Enhanced Speech Synthesis",
      "journal": "Journal of Information Systems Engineering and Management",
      "volume": "10",
      "year": "2025",
      "indexing": "Non Indexed",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2024-2025"
    },
    {
      "id": 15,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Precision Medicine and Personalized Healthcare: Interdisciplinary Approaches for Enhanced Patient Outcomes",
      "journal": "Journal of Neonatal Surgery",
      "volume": "14",
      "year": "2025",
      "indexing": "Non Indexed",
      "impactFactor": "0.16",
      "quartile": "",
      "doi": "",
      "academicYear": "2024-2025"
    },
    {
      "id": 16,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Artificial intelligence driven gender based text-to-speech systems(TTS) using deep learning algorithms",
      "journal": "International Journal of Speech Technology",
      "volume": "10",
      "year": "2025",
      "indexing": "SCOPUS",
      "impactFactor": "",
      "quartile": "Q1",
      "doi": "",
      "academicYear": "2024-2025"
    },
    {
      "id": 17,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Exploring Explainable Artificial Intelligence Techniques for Diabetic Retinopathy Detection using Grad-CAM and VGG16 Framework",
      "journal": "Journal of Neonatal Surgery",
      "volume": "14",
      "year": "2025",
      "indexing": "Non Indexed",
      "impactFactor": "0.16",
      "quartile": "",
      "doi": "",
      "academicYear": "2024-2025"
    },
    {
      "id": 18,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Diabetic Retinopathy Image Lesion Segmentation with Feature Fusion Relation Transformer Network",
      "journal": "Journal of Machine and Computing",
      "volume": "4",
      "year": "2024",
      "indexing": "SCOPUS",
      "impactFactor": "1.3",
      "quartile": "Q4",
      "doi": "",
      "academicYear": "2024-2025"
    },
    {
      "id": 19,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Quantum Convolutional Neural Networks for Line Orientation Classification in Pixelated Images",
      "journal": "Journal of Electrical Systems",
      "volume": "20",
      "year": "2024",
      "indexing": "Non Indexed",
      "impactFactor": "1.1",
      "quartile": "",
      "doi": "",
      "academicYear": "2023-2024"
    },
    {
      "id": 20,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Convolutional Neural Networks for Diabetic Retinopathy Detection in Retinal Images",
      "journal": "International Journal of Intelligent Systems and Applications in Engineering (IJISAE)",
      "volume": "12",
      "year": "2024",
      "indexing": "Non Indexed",
      "impactFactor": "1.3",
      "quartile": "",
      "doi": "",
      "academicYear": "2023-2024"
    },
   
    {
      "id": 22,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Deep Learning and Machine Learning Approach to Breast Cancer Classification with Random Search Hyperparameter Tuning",
      "journal": "International Journal of Intelligent Systems and Applications in Engineering",
      "volume": "12",
      "year": "2024",
      "indexing": "SCOPUS",
      "impactFactor": "3.847",
      "quartile": "Q4",
      "doi": "",
      "academicYear": "2023-2024"
    },
    {
      "id": 23,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Forecasting Vegetable Price Prediction Using GC-Attention Based- LSTM Approach",
      "journal": "International Conference on Self Sustainable Artificial Intelligence Systems, ICSSAS 2023",
      "volume": "",
      "year": "2023",
      "indexing": "SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2023-2024"
    },
    {
      "id": 24,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Enhancing Agricultural Decision-Making Through Machine Learning-Based Crop Yield Predictions",
      "journal": "International Conference on Data Science and Network Engineering, ICDSNE 2023",
      "volume": "791",
      "year": "2023",
      "indexing": "SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2023-2024"
    },
    {
      "id": 25,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Performance Analysis and Classification of Class Imbalanced Dataset Using Complement Naive Bayes Approach",
      "journal": "6th International Conference on Advanced Computing and Communication Technologies for High Performance Applications",
      "volume": "",
      "year": "2023",
      "indexing": "SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2022-2023"
    },
    {
      "id": 26,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Ant Colony Optimization in MANET for Decreasing Energy Consumption with ML Approaches",
      "journal": "2023 IEEE International Conference on Integrated Circuits and Communication Systems (ICICACS)",
      "volume": "",
      "year": "2023",
      "indexing": "SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2022-2023"
    },
    {
      "id": 27,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Analysis of Facial Expression using Deep Learning Techniques",
      "journal": "2023 IEEE International Conference on Integrated Circuits and Communication Systems (ICICACS)",
      "volume": "",
      "year": "2023",
      "indexing": "SCOPUS",
      "impactFactor": "",
      "quartile": "",
      "doi": "",
      "academicYear": "2022-2023"
    },
   
  ],
  "books": [
    {
      "id": 1,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Crop Prediction System with a Convolution Neural Network Model",
      "publisher": "Springer, Singapore",
      "type": "Book Chapter",
      "isbn": "978-981-19-7513-4",
      "year": "2023",
      "academicYear": "2022-2023"
    },
    {
      "id": 2,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Software Defect Prediction Using ROS-KPCA Stacked Generalization Model",
      "publisher": "Springer, Singapore",
      "type": "Book Chapter",
      "isbn": "978-981-19-7513-4",
      "year": "2023",
      "academicYear": "2022-2023"
    },
    {
      "id": 3,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Soft Computing",
      "publisher": "Scientific International Publishing house",
      "type": "Book",
      "isbn": "978-93-5757-554-6",
      "year": "2023",
      "academicYear": "2022-2023"
    },
    {
      "id": 4,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Classification of Brain Tumor Using Machine Learning Techniques: A Comparative Study",
      "publisher": "Wiley",
      "type": "Book Chapter",
      "isbn": "978-139421421-1",
      "year": "2024",
      "academicYear": "2023-2024"
    },
    {
      "id": 5,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "Explainable Artificial Intelligence (XAI) for Transparent Decision-Making",
      "publisher": "Leilani Katie Publication & Press",
      "type": "Book",
      "isbn": "978-93-6348-002-5",
      "year": "2026",
      "academicYear": "2025-2026"
    }
  ],
  "patents": [
    {
      "id": 1,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "ADVANCED WEB BROWSING ANALYTICS THROUGH NATURAL LANGUAGE PROCESSING",
      "applicationNo": "202221005812",
      "office": "Indian Patent Office",
      "status": "Granted",
      "filedDate": "03-02-2022",
      "grantedDate": "15-04-2022",
      "academicYear": "2021-2022"
    },
    {
      "id": 2,
      "empId": "7367",
      "name": "Dr M Bhaskar Marapelli",
      "title": "A Systematic Survey Using Machine Learning Techniques to Analyse the Efficacy of Just-In-Time Software Defect Prediction Systems",
      "applicationNo": "202341058541",
      "office": "Indian Patent Office",
      "status": "Published",
      "filedDate": "31-08-2023",
      "grantedDate": "08-09-2023",
      "academicYear": "2023-2024"
    }
 


  ],